# Generated by Django 4.0.3 on 2022-03-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpeps',
            name='cate',
            field=models.CharField(blank=True, choices=[('sea side', 'sea side'), ('beach', 'beach')], max_length=30, null=True),
        ),
    ]
