# Generated by Django 4.0.3 on 2022-03-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wallpeps_cate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpeps',
            old_name='cate',
            new_name='category',
        ),
    ]
